-- ── Seed Custom Name Keychain Template ──────────────────────────
-- Inserts the virtual keychain product into Supabase products table.
-- Copy and paste this script directly into the Supabase Dashboard SQL Editor and click 'Run'.

INSERT INTO public.products (
    id, 
    title, 
    description, 
    category, 
    "startingPrice", 
    "weightGrams", 
    "filamentUsage", 
    "isPreOrder", 
    "stockQuantity", 
    images, 
    colors, 
    materials, 
    tags, 
    "printTimeMinutes", 
    rating, 
    "reviewCount", 
    specifications, 
    resin_enabled, 
    resin_price,
    color_picker_count
) VALUES (
    'bv-keychain-template',
    'Custom Name Keychain',
    'Dynamic custom 3D printed keychain. Configured with custom text, font, size, and multi-color profiles.',
    'Keychains',
    150.0,
    10,
    10.0,
    false,
    -1,
    '["https://images.unsplash.com/photo-1614064641938-3bbee52942c7?auto=format&fit=crop&q=80&w=800"]'::jsonb,
    '["Matte Slate", "Chalk White", "Emerald Green", "Burnt Orange", "Obsidian Black", "Jade Green", "Silk Copper", "Neon Nebula"]'::jsonb,
    '["PLA (Matte)", "PETG (Durable)", "TPU (Flexible)"]'::jsonb,
    '["custom", "keychain"]'::jsonb,
    20,
    5.0,
    0,
    '{"dimensions": "80mm x 25mm x 4mm", "layerHeight": "0.16mm"}'::jsonb,
    true,
    50,
    2
) ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    "startingPrice" = EXCLUDED."startingPrice",
    "weightGrams" = EXCLUDED."weightGrams",
    "filamentUsage" = EXCLUDED."filamentUsage",
    "isPreOrder" = EXCLUDED."isPreOrder",
    "stockQuantity" = EXCLUDED."stockQuantity",
    images = EXCLUDED.images,
    colors = EXCLUDED.colors,
    materials = EXCLUDED.materials,
    "printTimeMinutes" = EXCLUDED."printTimeMinutes",
    resin_enabled = EXCLUDED.resin_enabled,
    resin_price = EXCLUDED.resin_price,
    color_picker_count = EXCLUDED.color_picker_count;
